PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS roles(id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT UNIQUE NOT NULL, description TEXT);
CREATE TABLE IF NOT EXISTS permissions(id INTEGER PRIMARY KEY AUTOINCREMENT, code TEXT UNIQUE NOT NULL, label TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS role_permissions(role_id INTEGER, permission_id INTEGER, PRIMARY KEY(role_id,permission_id), FOREIGN KEY(role_id) REFERENCES roles(id), FOREIGN KEY(permission_id) REFERENCES permissions(id));
CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT UNIQUE NOT NULL, password_hash TEXT NOT NULL, full_name TEXT, role_id INTEGER NOT NULL, active INTEGER DEFAULT 1, created_at TEXT DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(role_id) REFERENCES roles(id));
CREATE TABLE IF NOT EXISTS products(id INTEGER PRIMARY KEY AUTOINCREMENT, ref TEXT UNIQUE, name TEXT NOT NULL, category TEXT, unit TEXT DEFAULT 'Pièce', purchase_price REAL DEFAULT 0, sale_price REAL DEFAULT 0, quantity REAL DEFAULT 0, min_stock REAL DEFAULT 0, supplier_id INTEGER);
CREATE TABLE IF NOT EXISTS clients(id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, type TEXT DEFAULT 'particulier', ice TEXT, phone TEXT, city TEXT, address TEXT);
CREATE TABLE IF NOT EXISTS suppliers(id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, ice TEXT, phone TEXT, city TEXT, contact TEXT, address TEXT);
CREATE TABLE IF NOT EXISTS sales(id INTEGER PRIMARY KEY AUTOINCREMENT, date TEXT NOT NULL, client_id INTEGER, client_name TEXT, stage TEXT NOT NULL, numbers_json TEXT NOT NULL, lines_json TEXT NOT NULL, vat_rate REAL DEFAULT 20, total_ht REAL DEFAULT 0, vat REAL DEFAULT 0, total_ttc REAL DEFAULT 0, delivered INTEGER DEFAULT 0, payments_json TEXT DEFAULT '[]', created_by INTEGER, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS purchases(id INTEGER PRIMARY KEY AUTOINCREMENT, date TEXT NOT NULL, supplier_id INTEGER, supplier_name TEXT, stage TEXT NOT NULL, numbers_json TEXT NOT NULL, lines_json TEXT NOT NULL, vat_rate REAL DEFAULT 20, total_ht REAL DEFAULT 0, vat REAL DEFAULT 0, total_ttc REAL DEFAULT 0, received INTEGER DEFAULT 0, payments_json TEXT DEFAULT '[]', created_by INTEGER, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS counters(name TEXT PRIMARY KEY, value INTEGER DEFAULT 1);
INSERT OR IGNORE INTO roles(id,name,description) VALUES (1,'Administrateur','Accès total'),(2,'Gérant','Tout sauf gestion utilisateurs'),(3,'Vendeur','Ventes + clients + consultation stock'),(4,'Magasinier','Stock + achats/réceptions');
INSERT OR IGNORE INTO permissions(code,label) VALUES
('dashboard.read','Consulter tableau de bord'),('products.read','Consulter stock'),('products.write','Créer/modifier stock'),('products.delete','Supprimer produits'),('sales.read','Consulter ventes'),('sales.write','Créer/modifier ventes'),('sales.delete','Supprimer ventes'),('purchases.read','Consulter achats'),('purchases.write','Créer/modifier achats'),('purchases.delete','Supprimer achats'),('clients.read','Consulter clients'),('clients.write','Créer/modifier clients'),('suppliers.read','Consulter fournisseurs'),('suppliers.write','Créer/modifier fournisseurs'),('users.read','Consulter utilisateurs'),('users.write','Gérer utilisateurs');
INSERT OR IGNORE INTO role_permissions SELECT 1,id FROM permissions;
INSERT OR IGNORE INTO role_permissions SELECT 2,id FROM permissions WHERE code NOT LIKE 'users.%';
INSERT OR IGNORE INTO role_permissions SELECT 3,id FROM permissions WHERE code IN ('dashboard.read','products.read','sales.read','sales.write','clients.read','clients.write');
INSERT OR IGNORE INTO role_permissions SELECT 4,id FROM permissions WHERE code IN ('dashboard.read','products.read','products.write','purchases.read','purchases.write','suppliers.read','suppliers.write');
INSERT OR IGNORE INTO users(id,username,password_hash,full_name,role_id) VALUES (1,'admin','__ADMIN_HASH__','Administrateur',1);
INSERT OR IGNORE INTO counters(name,value) VALUES ('DEV',1),('BC',1),('BL',1),('FAC',1),('CF',1),('BR',1),('FF',1);
INSERT OR IGNORE INTO suppliers(id,name,ice,phone,city,contact) VALUES (1,'Sté Maghreb Peintures','001234567000045','0522-45-12-00','Casablanca','M. Alami'),(2,'Quincaillerie Atlas','002345678000067','0524-33-78-90','Marrakech','M. Bouzid');
INSERT OR IGNORE INTO clients(id,name,type,ice,phone,city,address) VALUES (1,'Client comptoir','particulier','','','',''),(2,'Ets Bennani BTP','entreprise','001987654000033','0661-22-33-44','Marrakech','Zone industrielle Sidi Ghanem');
INSERT OR IGNORE INTO products(id,ref,name,category,unit,purchase_price,sale_price,quantity,min_stock,supplier_id) VALUES
(1,'PEI-001','Peinture acrylique blanche 20L','Peinture','Pot',280,380,24,5,1),(2,'QUI-001','Vis aggloméré 4x40 boîte 200','Quincaillerie','Boîte',18,30,60,10,2),(3,'ELE-001','Fil électrique 2.5mm² rouleau 100m','Électricité','Rouleau',140,210,18,5,NULL),(4,'OUT-001','Perceuse à percussion 650W','Outillage','Pièce',320,450,8,3,NULL);
